### ISSUE TITLE
Great AddOn!

### ISSUE THREAD

**Issue by MJohnHBerry** [ddumont/seven#8]
Could you please give me one example of how to add job behaviors so they use WS's and such?

**Comment by ddumont** [comment]
oh hey... this notification got lost.

Yeah the behavior system was added by some friends and doesn't work the way i'd like.  Lemme look at it again and i'll send you some pointers

**Comment by ddumont** [comment]
what did you have in mind?

**Comment by ddumont** [comment]
Inactive for a long time
